import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <Link href="/">
            <a>Home</a>
          </Link>
        </li>
        <li>
          <Link href="/subpage">
            <a>Blog Post</a>
          </Link>
        </li>
        <li>
          <Link href="/subpage">
            <a>Subpage</a>
          </Link>
        </li>
      </ul>
    </div>
  );
}
